import { DetectorMetadata, SimulationScenario } from '../types';

export const DETECTORS_LIST: DetectorMetadata[] = [
  {
    id: 'portscan_hll',
    name: 'HyperLogLog Portscan Detector',
    shortName: 'HLL SCAN',
    category: 'Reconnaissance',
    algorithm: 'HyperLogLog Cardinality (b=14, p=99 threshold)',
    targetMetric: 'Unique Dst Ports / Source IP',
    mitreTechnique: 'T1595.001',
  },
  {
    id: 'dga_tunneling',
    name: 'DGA & DNS Tunneling Detector',
    shortName: 'DNS / DGA',
    category: 'C2 / Exfiltration',
    algorithm: 'Shannon Entropy + Length + N-gram Distribution',
    targetMetric: 'Entropy > 3.8, Subdomain Length > 45',
    mitreTechnique: 'T1568.002',
  },
  {
    id: 'encrypted_malware',
    name: 'Encrypted Malware & JA4 Fingerprinting',
    shortName: 'JA4 / TLS',
    category: 'Execution / Initial Access',
    algorithm: 'JA4 Fingerprint Hash + TLS Cipher Suite Profiling',
    targetMetric: 'Known C2 JA4 Match (Sliver/CobaltStrike)',
    mitreTechnique: 'T1071.001',
  },
  {
    id: 'c2_beaconing',
    name: 'Autoregressive C2 Beaconing Detector',
    shortName: 'C2 BEACON',
    category: 'Command & Control',
    algorithm: 'Inter-Arrival Time (IAT) FFT + Jitter Autocorrelation',
    targetMetric: 'Periodic Jitter < 15%, Interval 30-120s',
    mitreTechnique: 'T1071.001',
  },
  {
    id: 'exfil_ratio',
    name: 'Flow Volume & Exfiltration Ratio Detector',
    shortName: 'EXFIL RATIO',
    category: 'Exfiltration',
    algorithm: 'Asymmetric In/Out Byte Ratio & Outlier Mahalanobis',
    targetMetric: 'Out/In Ratio > 20:1, Vol > 50MB',
    mitreTechnique: 'T1048.002',
  },
  {
    id: 'ddos_entropy',
    name: 'Flow Entropy & Volumetric DDoS Detector',
    shortName: 'DDOS ENTROPY',
    category: 'Impact / Availability',
    algorithm: 'Sliding Window Header Entropy (IP/Port/Flags)',
    targetMetric: 'SYN Rate > 15,000 pps, Entropy < 1.2',
    mitreTechnique: 'T1498.001',
  },
];

export const MITRE_TECHNIQUES: Record<string, { name: string; tactic: string; phase: string; description: string }> = {
  'T1595.001': {
    name: 'Port Scanning (HyperLogLog)',
    tactic: 'Reconnaissance',
    phase: 'Reconnaissance',
    description: 'Adversary probes victim IP space to identify open ports using fast algorithmic enumeration.',
  },
  'T1595.002': {
    name: 'Vulnerability Scanning',
    tactic: 'Reconnaissance',
    phase: 'Reconnaissance',
    description: 'Adversary scans endpoints for exploitable software vulnerabilities prior to initial compromise.',
  },
  'T1568.002': {
    name: 'Domain Generation Algorithms (DGA)',
    tactic: 'Command and Control',
    phase: 'Command & Control',
    description: 'Adversary makes use of DGA-generated pseudo-random domains to establish resilient C2 infrastructure.',
  },
  'T1071.001': {
    name: 'Web Protocols (JA4 TLS / C2 Beaconing)',
    tactic: 'Command and Control',
    phase: 'Command & Control',
    description: 'Adversary communicates using application layer protocols over encrypted TLS with distinctive JA4 fingerprints.',
  },
  'T1048.002': {
    name: 'Exfiltration Over Asymmetric Network Protocol',
    tactic: 'Exfiltration',
    phase: 'Exfiltration',
    description: 'Adversary steals sensitive data by routing traffic over covert channels with high out/in volumetric ratios.',
  },
  'T1498.001': {
    name: 'Direct Network Flood (DDoS Entropy)',
    tactic: 'Impact',
    phase: 'Impact',
    description: 'Adversary floods target network infrastructure with high-rate packet bursts to deny availability.',
  },
  'T1046': {
    name: 'Network Service Discovery',
    tactic: 'Discovery',
    phase: 'Lateral Movement',
    description: 'Adversary attempts to get a listing of services running on remote hosts.',
  },
};

export const SIMULATION_SCENARIOS: SimulationScenario[] = [
  {
    id: 'apt',
    name: 'APT Multi-Stage Attack Chain',
    shortCode: 'APT-01',
    description: 'Complete Kill-Chain: HLL Port Scan -> Sliver C2 JA4 TLS -> DNS Tunneling Exfil',
    threatClasses: ['RECON', 'MALWARE_C2', 'EXFILTRATION'],
    expectedMitre: ['T1595.001', 'T1071.001', 'T1568.002', 'T1048.002'],
    severity: 'CRITICAL',
    stagesCount: 4,
  },
  {
    id: 'ddos',
    name: 'SYN Flood Volumetric DDoS',
    shortCode: 'DDOS-SYN',
    description: 'High-volume SYN flood with low flow entropy & sub-second line saturation',
    threatClasses: ['DDOS_VOLUMETRIC'],
    expectedMitre: ['T1498.001'],
    severity: 'CRITICAL',
    stagesCount: 1,
  },
  {
    id: 'c2',
    name: 'Sliver / Cobalt C2 Beaconing',
    shortCode: 'C2-BEACON',
    description: 'Periodic TLS beaconing with low jitter and JA4 fingerprint match',
    threatClasses: ['MALWARE_C2'],
    expectedMitre: ['T1071.001'],
    severity: 'HIGH',
    stagesCount: 2,
  },
  {
    id: 'dns_tunnel',
    name: 'DNS Tunneling & Base64 Exfiltration',
    shortCode: 'DNS-EXFIL',
    description: 'High Shannon entropy TXT/A queries encoding exfiltrated corporate records',
    threatClasses: ['DGA_TUNNELING', 'EXFILTRATION'],
    expectedMitre: ['T1568.002', 'T1048.002'],
    severity: 'HIGH',
    stagesCount: 2,
  },
  {
    id: 'portscan',
    name: 'Distributed Fast SYN Recon',
    shortCode: 'HLL-SCAN',
    description: 'Algorithmic cardinality burst scanning 1,024 ports across internal subnets',
    threatClasses: ['RECON'],
    expectedMitre: ['T1595.001'],
    severity: 'MEDIUM',
    stagesCount: 1,
  },
];
