import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CircleAlert, FileSearch, Gauge, LockKeyhole, Radio, ShieldCheck, Sparkles, Waves, X } from 'lucide-react';
import { FusedIncident, ScenarioId, SimulationResponse } from '../../types';
import { SIMULATION_SCENARIOS } from '../../utils/constants';

interface SimulationWalkthroughProps { scenario: ScenarioId; incident: FusedIncident | null; result: SimulationResponse | null; isSimulating: boolean; onBack: () => void; onToggleApproval: (incidentId: string) => void; }
const steps = [
  { title: 'Reconnaissance', label: 'External discovery', description: 'An external node maps the enclave perimeter. Passive sensors observe the scan without exposing a return path.', icon: Waves },
  { title: 'Weaponization', label: 'Payload preparation', description: 'Weak indicators are normalized into a structured flow record with network, TLS, and DNS context.', icon: FileSearch },
  { title: 'Command & control', label: 'Suspicious channel', description: 'The detection fabric identifies a periodic encrypted connection and links it to a known malicious fingerprint.', icon: Gauge },
  { title: 'Exfiltration', label: 'Covert transfer', description: 'Encoded data fragments move through DNS toward the external boundary. The signal accelerates as the risk rises.', icon: Sparkles },
  { title: 'Human review', label: 'Authorization gate', description: 'Multiple weak signals converge into one high-confidence incident. The response is held for operator approval.', icon: LockKeyhole },
  { title: 'Response', label: 'Controlled action', description: 'After approval, the countermeasure propagates through the one-way boundary and is recorded for audit.', icon: ShieldCheck },
];
const STEP_DURATION_MS = 2100;

export const SimulationWalkthrough: React.FC<SimulationWalkthroughProps> = ({ scenario, incident, result, isSimulating, onBack, onToggleApproval }) => {
  const [activeStep, setActiveStep] = useState(0);
  const [approvalDecision, setApprovalDecision] = useState<'pending' | 'approved' | 'rejected'>('pending');
  const scenarioInfo = useMemo(() => SIMULATION_SCENARIOS.find((item) => item.id === scenario), [scenario]);
  const current = steps[activeStep];
  const CurrentIcon = current.icon;
  const finished = Boolean(result && !isSimulating && activeStep === steps.length - 1 && approvalDecision === 'approved');
  const visibleEvents = incident?.timeline.slice(0, Math.min(activeStep + 1, incident.timeline.length)) ?? [];

  useEffect(() => { setActiveStep(0); setApprovalDecision('pending'); }, [scenario]);
  useEffect(() => {
    if (activeStep >= steps.length - 1 || (activeStep === 4 && approvalDecision !== 'approved') || finished) return;
    const timer = window.setTimeout(() => setActiveStep((step) => Math.min(step + 1, steps.length - 1)), STEP_DURATION_MS);
    return () => window.clearTimeout(timer);
  }, [activeStep, approvalDecision, finished]);
  const decideApproval = (decision: 'approved' | 'rejected') => { setApprovalDecision(decision); if (decision === 'approved' && incident) { onToggleApproval(incident.incident_id); setActiveStep(5); } };

  return <div className="walkthrough-page">
    <header className="walkthrough-topbar"><button className="back-button" onClick={onBack}><ArrowLeft size={16} /> Back to command center</button><div className="walkthrough-brand"><span className="status-dot pulse" /> SIH26145 <span>/</span> scenario replay</div><div className="walkthrough-status"><Radio size={14} /> <span>{isSimulating ? 'Executing' : finished ? 'Resolved' : 'Presentation mode'}</span></div></header>
    <main className="walkthrough-main">
      <section className="walkthrough-heading"><div className="heading-copy"><p className="walkthrough-overline">APT-01 · multi-stage attack</p><h1>{scenarioInfo?.name ?? 'Security scenario'}</h1><p className="walkthrough-summary">{scenarioInfo?.description ?? 'A controlled security event moving through the defense pipeline.'}</p></div><div className="run-badge"><span>Active scenario</span><strong>{scenarioInfo?.shortCode ?? scenario.toUpperCase()}</strong><small>{steps.length} synchronized stages</small></div></section>
      <section className="walkthrough-storyboard" aria-label="Simulation storyboard"><aside className="storyboard-rail"><div className="rail-heading"><span>Attack timeline</span><b>{String(activeStep + 1).padStart(2, '0')} / {String(steps.length).padStart(2, '0')}</b></div><div className="rail-line"><span style={{ height: `${((activeStep + 1) / steps.length) * 100}%` }} /></div><div className="storyboard-frames">{steps.map((step, index) => { const Icon = step.icon; const done = index < activeStep || finished; const selected = index === activeStep; const locked = index === 5 && approvalDecision !== 'approved'; return <button key={step.title} className={`storyboard-frame ${selected ? 'selected' : ''} ${done ? 'done' : ''} ${locked ? 'locked' : ''}`} aria-current={selected ? 'step' : undefined} disabled={locked} onClick={() => setActiveStep(index)}><span className="frame-number">{String(index + 1).padStart(2, '0')}</span><span className="frame-icon"><Icon size={16} /></span><span className="frame-copy"><strong>{step.title}</strong><em>{done ? 'Complete' : locked ? 'Approval required' : selected ? 'Playing now' : step.label}</em></span></button>; })}</div><div className="rail-footer"><span className="status-dot pulse" /> <span>{isSimulating ? 'Live simulation' : 'Replay ready'}</span></div></aside>
        <article className={`walkthrough-stage stage-${activeStep} ${finished ? 'resolved' : ''}`}><div className="stage-topline"><span>Architectural execution trace</span><span>{scenarioInfo?.shortCode ?? scenario.toUpperCase()}</span></div>
          <div className="stage-visual"><div className="defense-scene" aria-label="3D digital defense environment"><div className="scene-grid" /><div className="scene-ambient ambient-one" /><div className="scene-ambient ambient-two" /><div className="scene-zone external-zone"><span>External network</span></div><div className="scene-zone dmz-zone"><span>DMZ perimeter</span></div><div className="scene-zone enclave-zone"><span>Secure enclave</span></div><div className="scene-node attacker"><i /><span>External node</span></div><div className="scene-node sensor"><i /><span>Sensor bus</span></div><div className="scene-node diode"><i /><span>Data diode</span></div><div className="scene-node analyst"><i /><span>Operator</span></div><div className="scene-node engine"><i /><span>Detection fabric</span></div><div className="scene-path path-normal" /><div className="scene-path path-threat" /><div className="scene-path path-response" /><i className="scene-packet packet-one" /><i className="scene-packet packet-two" /><i className="scene-packet packet-three" /><i className="scene-packet packet-four" /><div className="scene-core"><CurrentIcon size={28} /><strong>{current.title}</strong><small>{finished ? 'Response recorded' : isSimulating ? 'Signal streaming' : 'Ready to replay'}</small></div><div className="scene-label scene-label-left">{incident?.source_ip ?? '198.51.100.44'} <b>source</b></div><div className="scene-label scene-label-right">{incident?.target_ips?.[0] ?? '10.0.1.15'} <b>protected asset</b></div><div className="scene-caption"><span>{current.label}</span><b>{incident ? `${visibleEvents.length} signals correlated` : 'Awaiting telemetry'}</b></div></div></div>
          <div className="stage-content"><div className="stage-kicker"><span>Now processing</span><b>{finished ? 'Complete' : `0${activeStep + 1} of 0${steps.length}`}</b></div><h2>{current.title}</h2><p>{current.description}</p><div className="evidence-strip"><div><span>{evidenceLabel(activeStep)}</span><strong>{evidenceValue(activeStep, scenarioInfo?.threatClasses, incident, finished)}</strong></div><code>{evidenceCode(activeStep, scenarioInfo?.expectedMitre, incident, finished)}</code></div>{activeStep === 4 && <div className={`approval-gate ${approvalDecision}`}><div className="approval-copy"><div className="approval-icon">{approvalDecision === 'rejected' ? <X size={17} /> : approvalDecision === 'approved' ? <Check size={17} /> : <LockKeyhole size={17} />}</div><div><strong>{approvalDecision === 'rejected' ? 'Response rejected' : approvalDecision === 'approved' ? 'Response approved' : 'Human authorization required'}</strong><span>{approvalDecision === 'rejected' ? 'The response remains blocked. Reconsider it to continue.' : approvalDecision === 'approved' ? 'The controlled response can now cross the one-way boundary.' : 'Review the proposed artifact before allowing the next step.'}</span></div></div><div className="approval-actions"><button className="approval-reject" onClick={() => decideApproval('rejected')}><X size={14} /> Reject</button><button className="approval-approve" disabled={!incident} onClick={() => decideApproval('approved')}><Check size={14} /> Approve response</button></div></div>}
            <div className="stage-detail-grid"><section className="trace-panel"><div className="detail-panel-heading"><span>Event trace</span><b>{incident ? `${incident.timeline.length} signals` : 'Awaiting signal'}</b></div>{visibleEvents.length ? visibleEvents.map((event) => <div className="trace-event" key={`${event.step_number}-${event.iso_time}`}><span className="trace-index">{String(event.step_number).padStart(2, '0')}</span><div><strong>{event.stage}</strong><p>{event.summary}</p></div><code>{`${(event.confidence * 100).toFixed(0)}%`}</code></div>) : <div className="trace-empty"><Radio size={15} /><span>Detector output will appear here as the simulation runs.</span></div>}</section><section className="decision-panel"><div className="detail-panel-heading"><span>Decision context</span><b>{incident?.severity ?? scenarioInfo?.severity ?? 'Pending'}</b></div><div className="decision-facts"><div><span>Source</span><strong>{incident?.source_ip ?? 'Sensor bus'}</strong></div><div><span>Targets</span><strong>{incident ? incident.target_ips.length : 'Queued'}</strong></div><div><span>Techniques</span><strong>{incident?.mitre_mappings.length ?? scenarioInfo?.expectedMitre.length ?? 0}</strong></div><div><span>Approval</span><strong>{incident?.requires_human_approval ? 'Required' : 'Pending'}</strong></div></div>{incident && <div className="countermeasure-line"><ShieldCheck size={14} /><span>{incident.countermeasures[0] ? `${incident.countermeasures[0].countermeasure_type} for ${incident.countermeasures[0].target_entity}` : 'Response artifact prepared'}</span></div>}</section></div>{finished && incident && <div className="completion-card"><div className="completion-icon"><Check size={18} /></div><div><strong>Scenario solved and recorded</strong><span>{incident.incident_id} is available in the investigation workspace.</span></div><b>{incident.risk_score.toFixed(0)}<small> risk</small></b></div>}</div>
          <footer className="stage-footer"><span>{finished ? <><Check size={14} /> Process complete</> : incident ? <><CircleAlert size={14} /> {incident.primary_threat_class} identified</> : <><Radio size={14} /> Listening for the next event</>}</span>{activeStep < steps.length - 1 && activeStep !== 4 && <button onClick={() => setActiveStep((step) => Math.min(step + 1, steps.length - 1))}>Next stage <ArrowRight size={14} /></button>}</footer>
        </article>
      </section>
    </main>
  </div>;
};

function evidenceLabel(step: number) { return ['Input', 'Enrichment', 'Detection', 'Risk score', 'Decision', 'Outcome'][step]; }
function evidenceValue(step: number, threatClasses: string[] | undefined, incident: FusedIncident | null, finished: boolean) { return ['Passive traffic stream', 'Flow record + JA4 fingerprint', threatClasses?.join(' + ') ?? 'Threat patterns', incident ? `${incident.risk_score.toFixed(0)} / 100` : 'Calculating compound score', 'Human authorization required', finished ? 'Countermeasure artifact prepared' : 'Awaiting approval gate'][step]; }
function evidenceCode(step: number, mitre: string[] | undefined, incident: FusedIncident | null, finished: boolean) { return ['TX TAP / ONE-WAY', 'ZEEK / TLS / DNS', mitre?.[0] ?? 'MITRE MATCH', incident ? `${incident.raw_alert_count} ALERTS FUSED` : 'WAITING FOR ALERTS', 'RETURN PATH: BLOCKED', finished ? 'AUDIT LOGGED' : 'DIODE LOCKED'][step]; }
